version: '3'
services:
  client:
    container_name: film-voting-client
    hostname: film-voting-client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 4000:4000
    links:
      - server
    networks:
      - app-connect
    depends_on:
      - server
    environment:
      SERVER: 'server:8000'
  server:
    container_name: film-voting-server
    hostname: film-voting-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:8000
    networks:
      - app-connect
networks:
  app-connect:
    driver: bridge